# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ea98f96035050fdb5898b2beda00c5ea731c0ac46b0ae6263a11b0edbcc4acbe9cfb9fc25191e43cf852a7c68aba8393d1ae9ba822faae5462563503b542012

test:
  secret_key_base: e588f2bc0407d6bf0a817b52606fd99d5868b0b2b42619bfd2104ab58ac9dfddbd7306624ccb4901cc933032058e3442da038b2b29d408d0df84782523e263e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
